In [2]:
!pip install numpy

In [0]:
import numpy as np
import time

Tipagem Multipla


In [4]:
x = [1, 1.2, 'a']
x

[1, 1.2, 'a']

In [5]:
np.array(x)

array(['1', '1.2', 'a'], dtype='<U32')

Tempo de execução

In [9]:
start = time.time()
time.sleep(0.5)
print(time.time() - start)

0.5008134841918945


In [12]:
start = time.time()

x = range(10000000)
y = range(10000000)
z = [x[i] + y[i]  for i in range(10000000)]

print(time.time() - start)

3.2644639015197754


In [13]:
start = time.time()

x = np.arange(10000000)
y = np.arange(10000000)
z = x + y

print(time.time() - start)

0.3005399703979492


numpy

In [16]:
x = list(range(10, 50, 2))
x

[10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48]

In [19]:
z = np.arange(10, 50, 2)
z

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [25]:
print(z[2])
print(z[5:])
print(z[:5])
print(z[2:5])
print(z[-1])
print(z[-2])


14
[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[10 12 14 16 18]
[14 16 18]
48
46


In [27]:
z[5:] = 100
z

array([ 10,  12,  14,  16,  18, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [31]:
np.arange(5, 201, 3)

array([  5,   8,  11,  14,  17,  20,  23,  26,  29,  32,  35,  38,  41,
        44,  47,  50,  53,  56,  59,  62,  65,  68,  71,  74,  77,  80,
        83,  86,  89,  92,  95,  98, 101, 104, 107, 110, 113, 116, 119,
       122, 125, 128, 131, 134, 137, 140, 143, 146, 149, 152, 155, 158,
       161, 164, 167, 170, 173, 176, 179, 182, 185, 188, 191, 194, 197,
       200])

In [35]:
z = np.arange(5, 201, 3).reshape((6, 11))
z

array([[  5,   8,  11,  14,  17,  20,  23,  26,  29,  32,  35],
       [ 38,  41,  44,  47,  50,  53,  56,  59,  62,  65,  68],
       [ 71,  74,  77,  80,  83,  86,  89,  92,  95,  98, 101],
       [104, 107, 110, 113, 116, 119, 122, 125, 128, 131, 134],
       [137, 140, 143, 146, 149, 152, 155, 158, 161, 164, 167],
       [170, 173, 176, 179, 182, 185, 188, 191, 194, 197, 200]])

In [36]:
z.shape

(6, 11)

In [38]:
print(z[2, 3])
print(z[1:4, 5:])


80
[[ 53  56  59  62  65  68]
 [ 86  89  92  95  98 101]
 [119 122 125 128 131 134]]


memoria

In [40]:
s = z[3:][:2]
s[:] = 100
s

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [41]:
z

array([[  5,   8,  11,  14,  17,  20,  23,  26,  29,  32,  35],
       [ 38,  41,  44,  47,  50,  53,  56,  59,  62,  65,  68],
       [ 71,  74,  77,  80,  83,  86,  89,  92,  95,  98, 101],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [170, 173, 176, 179, 182, 185, 188, 191, 194, 197, 200]])

In [43]:
f = s.copy()
f

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [44]:
f[:] = 10
f

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [45]:
s

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

Operações

In [46]:
z = np.arange(5, 201, 3).reshape((6, 11))
z

array([[  5,   8,  11,  14,  17,  20,  23,  26,  29,  32,  35],
       [ 38,  41,  44,  47,  50,  53,  56,  59,  62,  65,  68],
       [ 71,  74,  77,  80,  83,  86,  89,  92,  95,  98, 101],
       [104, 107, 110, 113, 116, 119, 122, 125, 128, 131, 134],
       [137, 140, 143, 146, 149, 152, 155, 158, 161, 164, 167],
       [170, 173, 176, 179, 182, 185, 188, 191, 194, 197, 200]])

In [48]:
z >= 50

array([[False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True]])

In [50]:
print(z[z > 50])
print(z[z % 2 == 0])
print(z[z % 5 == 0])

[ 53  56  59  62  65  68  71  74  77  80  83  86  89  92  95  98 101 104
 107 110 113 116 119 122 125 128 131 134 137 140 143 146 149 152 155 158
 161 164 167 170 173 176 179 182 185 188 191 194 197 200]
[  8  14  20  26  32  38  44  50  56  62  68  74  80  86  92  98 104 110
 116 122 128 134 140 146 152 158 164 170 176 182 188 194 200]
[  5  20  35  50  65  80  95 110 125 140 155 170 185 200]


In [51]:
z = np.linspace(5, 201, 30)
z

array([  5.        ,  11.75862069,  18.51724138,  25.27586207,
        32.03448276,  38.79310345,  45.55172414,  52.31034483,
        59.06896552,  65.82758621,  72.5862069 ,  79.34482759,
        86.10344828,  92.86206897,  99.62068966, 106.37931034,
       113.13793103, 119.89655172, 126.65517241, 133.4137931 ,
       140.17241379, 146.93103448, 153.68965517, 160.44827586,
       167.20689655, 173.96551724, 180.72413793, 187.48275862,
       194.24137931, 201.        ])

In [52]:
z.shape

(30,)

In [54]:
s = z.reshape(15, 2)
s

array([[  5.        ,  11.75862069],
       [ 18.51724138,  25.27586207],
       [ 32.03448276,  38.79310345],
       [ 45.55172414,  52.31034483],
       [ 59.06896552,  65.82758621],
       [ 72.5862069 ,  79.34482759],
       [ 86.10344828,  92.86206897],
       [ 99.62068966, 106.37931034],
       [113.13793103, 119.89655172],
       [126.65517241, 133.4137931 ],
       [140.17241379, 146.93103448],
       [153.68965517, 160.44827586],
       [167.20689655, 173.96551724],
       [180.72413793, 187.48275862],
       [194.24137931, 201.        ]])

matrizes aleatorias

In [55]:
np.random.randint(5, size=(3, 4))

array([[4, 3, 0, 1],
       [1, 2, 3, 0],
       [4, 1, 2, 1]])

In [58]:
np.random.rand(3, 4)

array([[0.46405468, 0.70928196, 0.35059321, 0.26714073],
       [0.21964355, 0.15023659, 0.70733996, 0.15157681],
       [0.72257942, 0.20165117, 0.81634873, 0.83323204]])

In [62]:
np.random.random_sample()

0.6250926066919551

In [65]:
a, b = 5, 10
(b - a) * np.random.random_sample((3, 4)) + a

array([[9.31000515, 8.09924324, 7.52715653, 5.32677403],
       [6.58573908, 8.57551102, 9.14700917, 6.15538432],
       [7.0247793 , 9.46656405, 6.67831208, 8.55598742]])

Operações

In [0]:
a, b = np.random.randint(15, size=(3, 4)), np.random.randint(5, 20, size=(3, 4))

In [70]:
type(a.tolist())

list

In [96]:
a

array([[11, 13,  7,  4],
       [ 3,  9,  8,  8],
       [ 7, 14, 11,  2]])

In [97]:
b

array([[16, 10, 17, 19],
       [15, 14, 11, 17],
       [ 7, 17, 17,  5]])

In [98]:
a + b

array([[27, 23, 24, 23],
       [18, 23, 19, 25],
       [14, 31, 28,  7]])

In [99]:
a - b

array([[ -5,   3, -10, -15],
       [-12,  -5,  -3,  -9],
       [  0,  -3,  -6,  -3]])

In [100]:
a * b

array([[176, 130, 119,  76],
       [ 45, 126,  88, 136],
       [ 49, 238, 187,  10]])

In [101]:
a / b

array([[0.6875    , 1.3       , 0.41176471, 0.21052632],
       [0.2       , 0.64285714, 0.72727273, 0.47058824],
       [1.        , 0.82352941, 0.64705882, 0.4       ]])

In [0]:
a, b = np.random.randint(15, size=(3, 4)), np.random.randint(5, 20, size=(4, 3))

In [92]:
np.matmul(a, b)

array([[452, 389, 415],
       [432, 369, 412],
       [492, 449, 480]])

In [0]:
a = np.random.randint(15, size=(3, 3))

In [105]:
np.linalg.det(a)

-78.00000000000007

In [106]:
np.linalg.inv(a)

array([[ 1.48717949, -0.58974359,  0.07692308],
       [-2.16666667,  0.83333333,  0.        ],
       [ 1.5       , -0.5       ,  0.        ]])